{% set prefix = "spacy-model-" %}
{% set lang = "es" %}

{% if size == "trf" %}
{% set name = lang + "_dep_news" %}
{% else %}
{% set name = lang + "_core_news" %}
{% endif %}

{% set version = "3.5.0" %}


package:
  name: {{ prefix }}{{ lang|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-{{ version }}/es_core_news_sm-{{ version }}.tar.gz
    sha256: ca34941919517e5144ee2990f133f9affd9ed6b4993f9fa882330fcbbb783d99
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/es_core_news_md-{{ version }}/es_core_news_md-{{ version }}.tar.gz
    sha256: 032b66e7dfbc2d36909a75fbf14997214c06074603836d73c2501aed5bd4bdac
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/es_core_news_lg-{{ version }}/es_core_news_lg-{{ version }}.tar.gz
    sha256: 7dfec92e53e5680ce76c757a3aa905fb1c71eda32c22a479fb37c1e715fa867f
  - folder: trf
    url: https://github.com/explosion/spacy-models/releases/download/es_dep_news_trf-{{ version }}/es_dep_news_trf-{{ version }}.tar.gz
    sha256: 22a87a48824d7529daa1e7f28d94d0a54ad31abdf0b06bb651a5f766d844c9df

build:
  number: 0

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}

    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
        {% if size == "trf" %}
        - spacy-transformers  # [unix]
        {% endif %}
      commands:
        {% if size == "trf" %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"  # [unix]
        {% else %}
        - python -c "import {{ name }}_{{ size }} as m; m.load()"
        - python -c "import spacy; spacy.load('{{ name }}_{{ size }}')"
        {% endif %}
about:
  home: https://spacy.io
  license: CC-BY-SA-3.0
  summary: Spanish multi-task CNN trained on the AnCora and WikiNER corpus
  license_file: LICENSE
  doc_url: https://spacy.io/models/es

extra:
  recipe-maintainers:
    - FernandezMathieu
    - JennaLipscomb
    - sodre
    - mxr-conda
